name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  csr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
          run_install: true

      - name: Build project
        run: |
          echo install dependencies
          pnpm i
          echo build project
          pnpm build:spa

      - name: Upload website to Aliyun OSS
        uses: ncuhome/ali-oss-website-action@v1.1.0
        id: upload
        with:
          folder: dist # 待上传的文件夹
          accessKeyId: ${{ secrets.ACCESSKEYID }} ## 通过 secrets 注入 ak
          accessKeySecret: ${{ secrets.ACCESSKEYSECRET }}
          bucket: team-site # 要上传到的 bucket, 若不存在会自动新建
          endpoint: oss-cn-shanghai.aliyuncs.com # 指定区域的 oss endpoint
          incremental: true # 开启增量上传，只上传 md5 值变化、新增、删除 的文件

  ssr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to NCUOS Registry
        uses: docker/login-action@v1
        with:
          registry: midway.ncuos.com
          username: ${{ secrets.NCUOS_REGISTRY_USERNAME }}
          password: ${{ secrets.NCUOS_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.ncuos.com/ncuhome-main-site:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Redeploy
        uses: kuhsinyv/rancher-workloads-redeploy-action@v1.2
        env:
          API_ACCESS_ADDR: https://rancher.ncuos.com/v3
          CLUSTER: local
          PROJECT: p-qld78
          NAMESPACE: us
          WORKLOAD: us:ncuhome-team-site
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
