name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  csr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          pnpm i

      - name: Build project
        run: |
          pnpm build

      - name: Upload website to Aliyun OSS
        uses: ncuhome/ali-oss-website-action@v1.1.0
        id: upload
        with:
          folder: dist # 待上传的文件夹
          accessKeyId: ${{ secrets.ACCESSKEYID }} ## 通过 secrets 注入 ak
          accessKeySecret: ${{ secrets.ACCESSKEYSECRET }}
          bucket: team-site # 要上传到的 bucket, 若不存在会自动新建
          endpoint: https://oss-cn-shanghai.aliyuncs.com # 指定区域的 oss endpoint
          incremental: true # 开启增量上传，只上传 md5 值变化、新增、删除 的文件
