name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  csr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm i

      - name: Build project
        run: |
          pnpm build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: harbor.ncuos.com/new-team/old-team

      - name: Build Docker Image and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Deployment
        uses: MultiMx/K8sSetImageAction@v0.5
        with:
          backend: "https://rancher.ncuos.com"
          token: ${{ secrets.RANCHER_TOKEN }}
          namespace: team-2025
          workload: old-team
          image: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
